### ISSUE TITLE
Unchecked runtime.lastError

### ISSUE THREAD

**Issue by davidb1** [larscom/angular-chrome-extension#1]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

Getting this error when clicking the button to send the message, no answer is received

Probably missing the connect part as per:
[https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi](https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi)

**Comment by kmiskiewicz** [comment]
I created pull request with fix, please take a look :-)

**Comment by larscom** [comment]
hi @davidb1 are you trying to send the message inside chrome://extensions ? or some other google page?
The browser is blocking access to the content page...
Try sending a message from another webpage :)

**Comment by kmiskiewicz** [comment]
Hi, I also experience this issue...however maybe it's a correct situation (I'm newbie in extensions development -wanted to look at working example before I'll dig into the documentation ).
After the plugin installation is necessary to refresh the page, in other case the extension will display the error. 
I use: Version 72.0.3626.121 (Official Build) (64-bit)
ps. I tried also with modifying the manifest but it doesn't change anything https://developer.chrome.com/extensions/manifest/externally_connectable
