### ISSUE TITLE
Importing modules in backgroundPage.ts

### ISSUE THREAD

**Issue by michaelvobejda** [larscom/angular-chrome-extension#16]
Thanks so much for the great template, it's been super helpful. 

One quick question. How can I import node modules into backgroundPage.ts and contentPage.ts? 

I see that they're included as entrypoints in the build, but I haven't been able to require modules in these scripts.

Thanks in advance!

**Comment by mshinoy** [comment]
I have a similar issue, I would like to modify the DOM from a click on the contextmenu.
Is that possible to do it from within angular or do I need to do it from within the content page? 

If from the contentPage.ts. How do i get MatDialogBox to show up there?

**Comment by chan-dev** [comment]
one possible solution is to move all `chrome` related files inside `angular/src` and update `tsconfig.app.json`  so they will be included when files are built.
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": ["@types/chrome"]
  },
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.d.ts", "src/chrome/**/*.ts"]
}
```

This way those files will share the same tsconfig setting. You might as well delete the `chrome/tsconfig.json` and update custom webpack config files accordingly.

**Comment by larscom** [comment]
I've made some updates to the project. 
When you now create a new extension with the CLI tool:

`ng-chrome`

You can now import modules the same way as you would do in angular.

example in serviceWorker.ts:

```
import { of } from 'rxjs';

of('Hello World!').subscribe(console.log);
```
