### ISSUE TITLE
The dependencies are broken

### ISSUE THREAD

**Issue by ezhupa99** [larscom/angular-chrome-extension#39]
I cloned the repo and then I tried to install the dependencies and then this happened

![image](https://user-images.githubusercontent.com/34006441/187051732-d4000114-c706-4675-b013-eb6938882470.png)

**Comment by larscom** [comment]
Hi,

please use `npm ci --legacy-peer-deps` or (preferably) use the CLI tool to generate a new chrome extension:

**Install CLI**

```shell
npm install -g @larscom/ng-chrome-extension
```

**Generate a new extension**

```shell
ng-chrome
```

**Comment by Farley-Chen** [comment]
`npm install xxx --legacy-peer-deps`  or ``npm install --legacy-peer-deps`` helps me to solve the problem
