### ISSUE TITLE
Why is it necessary to use ChangeDetectorRef?

### ISSUE THREAD

**Issue by kaihaase-wd** [larscom/angular-chrome-extension#4]
Thank you for the great template. It is a very good help to start a Chrom Extension project with Angular.

However, using ChangeDetectorRef is a bit cumbersome. Has automatic change detection been deliberately deactivated or is it technically impossible to do otherwise?

**Comment by larscom** [comment]
Hi,

I don't have an answer directly for you why this is happening. Maybe because angular doesn't see the chrome.tabs.sendMessage callback in combination with the message subject as a change..

It should be possible to use without ChangeDetectorRef though.

Good luck!
