### ISSUE TITLE
Refreshing on DevTools

### ISSUE THREAD

**Issue by brab0** [larscom/angular-chrome-extension#6]
You should fix base href to <base href=\"#/\">. Then HashLocationStrategy can work properly.

**Comment by larscom** [comment]
What version of Angular are you using?

**Comment by brab0** [comment]
Angular 7

**Comment by larscom** [comment]
I'm using the HashLocationStrategy with Angular 7 and default base href without problems..
Do you get any error or something?

**Comment by upadmdh** [comment]
When using `chrome_url_overrides` for the extension to take over the new tab page, initial load works fine. But when you refresh the new tab page the browser throws a 404.

1. Browser go to `chrome-extension://hkmmlaghihcdhmpodgfnkkjbmecahifc/index.html`
2. Angular routing with `HashLocationStrategy` kicks in and changes url to `chrome-extension://hkmmlaghihcdhmpodgfnkkjbmecahifc/dist/app/#/`. The app works at this point.
3. I refresh the page and get 404 as browser is trying to go to `chrome-extension://hkmmlaghihcdhmpodgfnkkjbmecahifc/dist/app/#/browse` straight without loading the `index.html`

@larscom I am not sure if @brab0 had faced the same issue which I did, but nevertheless, his suggestion did fix it for me.

Maybe specify in the docs for when the extension is being loaded in a page, the `base-href` needs to be updated

**Comment by larscom** [comment]
Thanks for the explanation! will update the docs for this :smiley:
