### ISSUE TITLE
I need some help for new tab

### ISSUE THREAD

**Issue by reactsuperwizard** [larscom/angular-chrome-extension#7]
Hello.
I  want to create "new tab" for my "dashboard" from popup.
I tried several times as followed as your word in readme.md.
I am new here so I didn't make sense clearly yet.

Please let me know how to do it.
I will share my source code .
I wish to /report redirect.
/report

manifest.json file:
{
  "manifest_version": 2,
  "name": "Angular Chrome Extension",
  "short_name": "Angular Chrome Extension",
  "version": "1.0.0",
  "description": "Angular Chrome Extension scaffold project",
  "permissions": ["tabs"],
  "chrome_url_overrides": {
    "newtab": "/report"
  },
  "browser_action": {
    "default_popup": "index.html",
    "default_title": "Angular Chrome Extension"
  },
  "content_scripts": [{
    "js": ["contentPage.js"],
    "matches": ["<all_urls>"]
  }],
  "background": {
    "scripts": ["backgroundPage.js"],
    "persistent": false
  },
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
}

-backgroundPage.ts
console.log('background script loaded');
chrome.browserAction.onClicked.addListener(function (activeTab) {
  var newURL = "chrome://newtab";
  chrome.tabs.create({ url: newURL });
});

app-routing.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { PopupComponent } from './components/popup/popup.component';
import { ReportComponent } from './components/report/report.component';
import { HistoryComponent } from './components/history/history.component';

const routes: Routes = [
  { path: 'popup', component: PopupComponent },
  { path: 'report/home', component: ReportComponent },
  { path: 'report/kpi', component: ReportComponent },
  { path: 'report/optimization', component: ReportComponent },
  { path: 'report/compsnapshot', component: ReportComponent },
  { path: 'report/detail', component: ReportComponent },
  { path: 'report/evolution', component: ReportComponent },
  { path: 'report/importdef', component: ReportComponent },
  { path: 'report/importmap', component: ReportComponent },
  { path: 'report/moduleauoc', component: ReportComponent },
  { path: 'report/wsauic', component: ReportComponent },
  { path: 'report/auditreport', component: ReportComponent },
  { path: 'report/wsauic', component: ReportComponent },
  { path: 'report/oprinreco', component: ReportComponent },
  { path: 'report', redirectTo: '/report/home' },
  { path: 'optimization', component: PopupComponent },
  { path: 'snapshot', component: PopupComponent },
  { path: 'history', component: HistoryComponent },
  // { path: '**', redirectTo: '/report/detail' }
  { path: '**', redirectTo: '/popup' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: true })],
  exports: [RouterModule]
})
export class AppRoutingModule { }

**Comment by larscom** [comment]
Hi, what is the problem you are facing?
